# Generated by Django 5.2.4 on 2025-08-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_country_alter_vendor_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='wallet_linked',
            field=models.BooleanField(default=False),
        ),
    ]
