# Generated by Django 5.2.4 on 2025-08-15 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_wallet_linked'),
    ]

    operations = [
        migrations.AddField(
            model_name='kyc',
            name='id_document',
            field=models.FileField(blank=True, null=True, upload_to='kyc/id_docs/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='kyc/selfies/'),
        ),
    ]
