# Generated by Django 5.2.4 on 2025-08-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_customuser_bonus_amount_activetrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profit_today',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
