# Generated by Django 5.2.4 on 2025-08-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_customuser_profit_today'),
    ]

    operations = [
        migrations.AddField(
            model_name='activetrade',
            name='closed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activetrade',
            name='created_by',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=5),
        ),
    ]
