# Generated by Django 5.2.4 on 2025-08-20 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_activetrade_closed_at_activetrade_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletsettings',
            name='support_email',
            field=models.EmailField(blank=True, help_text='Shown in the deposit popup.', max_length=254, null=True),
        ),
    ]
