# Generated by Django 5.2.4 on 2025-08-22 12:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_walletsettings_support_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(blank=True, max_length=120)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('account_number', models.CharField(blank=True, max_length=120)),
                ('routing_or_swift', models.CharField(blank=True, max_length=120)),
                ('country', models.CharField(blank=True, max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
