# Generated by Django 5.2.4 on 2025-08-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_bankinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accountwithdrawal',
            name='account_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='accountwithdrawal',
            name='account_number',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='accountwithdrawal',
            name='bank_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='accountwithdrawal',
            name='country',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='accountwithdrawal',
            name='method',
            field=models.CharField(choices=[('btc', 'Bitcoin'), ('eth', 'Ethereum'), ('usdt_trc20', 'USDT (TRC20)'), ('bank', 'Bank Transfer')], default='btc', max_length=20),
        ),
        migrations.AddField(
            model_name='accountwithdrawal',
            name='routing_or_swift',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='accountwithdrawal',
            name='us_account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='accountwithdrawal',
            name='us_ssn',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
