# Generated by Django 5.2.4 on 2025-08-23 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_accountwithdrawal_account_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='us_account_type',
            field=models.CharField(blank=True, choices=[('checking', 'Checking'), ('savings', 'Savings')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='bankinfo',
            name='us_ssn',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
