# Generated by Django 5.2.4 on 2025-08-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_experttrader_copysubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='current_plan',
            field=models.CharField(choices=[('mini', 'Mini'), ('starter', 'Starter'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('diamond', 'Diamond'), ('gold', 'Gold')], default='mini', max_length=20),
        ),
        migrations.AddField(
            model_name='customuser',
            name='pending_plan',
            field=models.CharField(blank=True, choices=[('mini', 'Mini'), ('starter', 'Starter'), ('bronze', 'Bronze'), ('silver', 'Silver'), ('diamond', 'Diamond'), ('gold', 'Gold')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='upgrade_progress',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
