# Generated by Django 5.2.4 on 2025-08-31 23:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_customuser_current_plan_customuser_pending_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminMailout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body_html', models.TextField(help_text='You can paste basic HTML. This will be wrapped in the standard email template.')),
                ('segment', models.CharField(choices=[('ALL', 'All users'), ('NO_DEPOSIT', 'Users without any deposit'), ('SPECIFIC', 'Specific users only')], default='ALL', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_count', models.PositiveIntegerField(default=0)),
                ('is_sent', models.BooleanField(default=False)),
                ('recipients', models.ManyToManyField(blank=True, help_text="Used only when segment is 'Specific users'", to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
