# Generated by Django 5.2.4 on 2025-08-31 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_adminmailout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='upgrade_note',
            field=models.TextField(blank=True, help_text='Optional note/reason for upgrade decisions'),
        ),
    ]
