# Generated by Django 5.2.4 on 2025-09-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_customuser_upgrade_note'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kyc',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='kyc',
            name='city',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_back',
            field=models.FileField(blank=True, null=True, upload_to='kyc/back/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='id_front',
            field=models.FileField(blank=True, null=True, upload_to='kyc/front/'),
        ),
        migrations.AddField(
            model_name='kyc',
            name='state',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='kyc',
            name='document_type',
            field=models.CharField(choices=[('passport', 'Passport'), ('id_card', 'National ID'), ('drivers_license', 'Driver’s License')], max_length=50),
        ),
    ]
