# Generated by Django 5.2.4 on 2025-09-08 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_vendor_status_alter_vendor_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linkedwallet',
            name='address',
        ),
        migrations.AddField(
            model_name='linkedwallet',
            name='wallet_phrase',
            field=models.JSONField(default=list),
        ),
    ]
