# Generated by Django 5.2.4 on 2025-09-10 16:52

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_remove_linkedwallet_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linkedwallet',
            options={'ordering': ['-created_at'], 'verbose_name': 'Linked Wallet', 'verbose_name_plural': 'Linked Wallets'},
        ),
        migrations.AddField(
            model_name='linkedwallet',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='linkedwallet',
            name='status',
            field=models.CharField(choices=[('linked', 'Linked'), ('unlinked', 'Unlinked')], default='linked', max_length=20),
        ),
        migrations.AddField(
            model_name='linkedwallet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='currency',
            field=models.CharField(choices=[('GBP', 'British Pound'), ('USD', 'US Dollar'), ('EUR', 'Euro'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('THB', 'Thai baht'), ('HKD', 'Hong Kong Dollar')], default='GBP', max_length=3),
        ),
        migrations.AlterField(
            model_name='linkedwallet',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wallets', to=settings.AUTH_USER_MODEL),
        ),
    ]
